# Generated by Django 3.0.2 on 2020-02-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laureats', '0013_auto_20200111_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laureat',
            name='sexe',
            field=models.CharField(choices=[(1, 'Masculin'), (2, 'Feminin'), (2, 'Autre')], default='', max_length=50),
        ),
    ]
